### ISSUE TITLE
Investigate to use latest version of minikube for linux

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-kubernetes-intro#171]
The latest version of minikube for Linux may not need to do following:
`eval $(minikube docker-env)`

**Comment by AustinSeto** [comment]
The issue experienced by `eval $(minikube docker-env)` in our GitHub Actions tests occurs because the `none` driver is used for Minikube. This driver is used by users with root privileges on VMs. I think there should be no issue if using Linux on a non-virtual machine if the user is using a different Minikube driver. 

I think this should be verified on a physical Linux machine still.

**Comment by gkwan-ibm** [comment]
close because no need to fix
